### ISSUE TITLE
无法显示设置

### ISSUE THREAD

**Issue by 774216-RGB** [xh321/LiteLoaderQQNT-Anti-Recall#103]
防撤回功能有效，但无法查看设置。
![6d2fb6c09c514b54e9b1c6b0e36c229c](https://github.com/user-attachments/assets/a0aa1a39-c28c-49f7-992d-7f830360a620)

**Comment by xh321** [comment]
请检查是否包含不兼容插件，设置界面可能因为其他插件报错导致白屏，建议只启用防撤回一个插件试试

**Comment by 774216-RGB** [comment]
只用那一个插件试过了，没用

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: XiaoHe321 ***@***.***>
发送时间: Thursday, November 28, 2024 11:48:25 AM
收件人: xh321/LiteLoaderQQNT-Anti-Recall ***@***.***>
抄送: 774216-RGB ***@***.***>; Author ***@***.***>
主题: Re: [xh321/LiteLoaderQQNT-Anti-Recall] 无法显示设置 (Issue #103)


请检查是否包含不兼容插件，设置界面可能因为其他插件报错导致白屏，建议只启用防撤回一个插件试试

―

**Comment by xh321** [comment]
有可能是QQ版本太高，可以说一下你的版本
并且用命令行执行一下QQ
QQ --enable-logging
应该会有渲染层的报错，如有，麻烦贴在下面

**Comment by 774216-RGB** [comment]
学生党，电脑被收了，QwQ

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: XiaoHe321 ***@***.***>
发送时间: Thursday, November 28, 2024 8:03:06 PM
收件人: xh321/LiteLoaderQQNT-Anti-Recall ***@***.***>
抄送: 774216-RGB ***@***.***>; Author ***@***.***>
主题: Re: [xh321/LiteLoaderQQNT-Anti-Recall] 无法显示设置 (Issue #103)


有可能是QQ版本太高，可以说一下你的版本
并且用命令行执行一下QQ
QQ --enable-logging
应该会有渲染层的报错，如有，麻烦贴在下面

―

**Comment by MaShuSO** [comment]
同上，我用的是archlinux。直接启动在命令行中会有以下日志
```
[Mashu@archlinux ~]$ linuxqq --enable-logging
User flags: --ozone-platform-hint=auto --enable-wayland-ime
not mini app. 
version_config_filename :/home/Mashu/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :38626
config_base_version :3.2.19-38626
config_current_version :3.2.19-38626
app_build_version :38626
version_config_filename :/home/Mashu/.config/QQ/versions/config.json
version_config_filename :/home/Mashu/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :38626
config_base_version :3.2.19-38626
config_current_version :3.2.19-38626
app_build_version :38626
config_build_id :38626
config_base_version :3.2.19-38626
config_current_version :3.2.19-38626
app_build_version :38626
[preload] succeeded. /opt/QQ/resources/app/major.node
[preload] succeeded. /opt/QQ/resources/app/major.node
resourcesPath: /opt/QQ/resources
[LiteLoader] Found Plugin: 插件列表查看
[LiteLoader] Found Plugin: 防撤回
(node:3973) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/opt/LiteLoaderQQNT/data/anti_recall'
    at Object.mkdirSync (node:fs:1371:26)
    at onLoad (/opt/LiteLoaderQQNT/plugins/qq-anti-reccall/main.js:46:8)
    at Object.<anonymous> (/opt/LiteLoaderQQNT/plugins/qq-anti-reccall/main.js:42:1)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at f._load (node:electron/js2c/node_init:2:18418)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
(Use `qq --trace-warnings ...` to show where the warning was created)
(node:3973) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[3973:0828/205249.474605:WARNING:wayland_object.cc(179)] Binding to wl_shm version 1 but version 2 is available.
[3973:0828/205249.474633:WARNING:wayland_object.cc(179)] Binding to wl_seat version 8 but version 9 is available.
[3973:0828/205249.474652:WARNING:wayland_object.cc(179)] Binding to zwp_pointer_gestures_v1 version 1 but version 3 is available.
[3973:0828/205249.474686:WARNING:wayland_object.cc(179)] Binding to wp_cursor_shape_manager_v1 version 1 but version 2 is available.
[3973:0828/205249.474800:WARNING:wayland_object.cc(179)] Binding to zwp_linux_dmabuf_v1 version 3 but version 5 is available.
[3973:0828/205249.625879:WARNING:wayland_surface.cc(200)] Server doesn't support zcr_alpha_compositing_v1.
[3973:0828/205249.625901:WARNING:wayland_surface.cc(215)] Server doesn't support overlay_prioritizer.
[3973:0828/205249.625908:WARNING:wayland_surface.cc(231)] Server doesn't support surface_augmenter.
[3973:0828/205249.625915:WARNING:wayland_surface.cc(265)] Server doesn't support zcr_color_management_surface.
pci id for fd 21: 10de:137b, driver (null)
kmsro: driver missing
[4017:0828/205249.842828:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.
[4017:0828/205249.843666:WARNING:viz_main_impl.cc(85)] VizNullHypothesis is disabled (not a warning)
[3973:0828/205249.899503:ERROR:gpu_process_host.cc(981)] GPU process exited unexpectedly: exit_code=9
[3973:0828/205249.899528:WARNING:gpu_process_host.cc(1418)] The GPU process has crashed 1 time(s)
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:87136)
    at WebContents.emit (node:events:518:28)
[4026:0828/205250.062242:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
pci id for fd 21: 10de:137b, driver (null)
kmsro: driver missing
[4062:0828/205250.101737:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.
[4062:0828/205250.102567:WARNING:viz_main_impl.cc(85)] VizNullHypothesis is disabled (not a warning)
[3973:0828/205250.103265:WARNING:gpu_process_host.cc(1003)] Reinitialized the GPU process after a crash. The reported initialization time was 200 ms
[3973:0828/205250.125023:ERROR:gpu_process_host.cc(981)] GPU process exited unexpectedly: exit_code=9
[3973:0828/205250.125043:WARNING:gpu_process_host.cc(1418)] The GPU process has crashed 2 time(s)
pci id for fd 21: 10de:137b, driver (null)
kmsro: driver missing
[4085:0828/205250.335707:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.
[4085:0828/205250.336713:WARNING:viz_main_impl.cc(85)] VizNullHypothesis is disabled (not a warning)

(qq:3973): VIPS-WARNING **: 20:52:50.577: unable to load "/usr/lib/vips-modules-8.17/vips-poppler.so" -- libpoppler-glib.so.8: 无法打开共享目标文件: 没有那个文件或目录

(qq:3973): VIPS-WARNING **: 20:52:50.578: unable to load "/usr/lib/vips-modules-8.17/vips-heif.so" -- libheif.so.1: 无法打开共享目标文件: 没有那个文件或目录

(qq:3973): VIPS-WARNING **: 20:52:50.589: unable to load "/usr/lib/vips-modules-8.17/vips-magick.so" -- libMagickCore-7.Q16HDRI.so.10: 无法打开共享目标文件: 没有那个文件或目录
[3973:0828/205250.707998:WARNING:gpu_process_host.cc(1003)] Reinitialized the GPU process after a crash. The reported initialization time was 207 ms
[3973:0828/205250.863557:ERROR:gpu_process_host.cc(981)] GPU process exited unexpectedly: exit_code=9
[3973:0828/205250.863591:WARNING:gpu_process_host.cc(1418)] The GPU process has crashed 3 time(s)
[4131:0828/205251.027898:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.
[4131:0828/205251.028910:WARNING:viz_main_impl.cc(85)] VizNullHypothesis is disabled (not a warning)
[3973:0828/205251.030105:WARNING:gpu_process_host.cc(1003)] Reinitialized the GPU process after a crash. The reported initialization time was 161 ms
[1][270762446]DroppedFrame(1): host_id=1, time=270728460, latest_seq=22, interval=16659
linux-bugly: init bugly ...
InitBuglyManager
SetLogger
fatalSetup
GetDllPath: 33
pub_key_path: /opt/QQ/resources/app/pub.key
[BuglyManager.cpp][InitBuglyManager][212]InitBuglyManager path: /home/Mashu/.config/QQ/crash_files/
BuglyManager/opt/QQ/resources/app/pub.key
[BuglyService.cpp][registBugly][589]set signal stack
[BuglyService.cpp][registSignalHandler][520]regist native handler
registBugly/opt/QQ/resources/app/pub.key
[BuglyService.cpp][setParam][618]setParam, key:appVersion, value:3.2.19-38626..
setParam/opt/QQ/resources/app/pub.key
StartWithOptions s/opt/QQ/resources/app/pub.key
StartWithOptions e/opt/QQ/resources/app/pub.key
PostDelayedTask s/opt/QQ/resources/app/pub.key
PostDelayedTask e/opt/QQ/resources/app/pub.key
linux-bugly: init bugly done.
[3973:0828/205253.743548:INFO:perf_util.cc(137)] ListenLowPerformanceNotification: policy=(60, 10, 5, 200, 5000), severe_slot=49, isolate=0x33ac002c4000, has_context=1
[3973:0828/205254.022837:INFO:CONSOLE(0)] "windowSetup sandboxed: undefined", source: node:electron/js2c/sandbox_bundle (0)
[3973:0828/205254.022889:INFO:CONSOLE(0)] "windowSetup isWebView: false", source: node:electron/js2c/sandbox_bundle (0)
[4131:0828/205254.669053:ERROR:gles2_cmd_decoder_passthrough.cc(1093)] [GroupMarkerNotSet(crbug.com/242999)!:A0B01900EC060000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content.
[4131:0828/205254.682925:ERROR:gles2_cmd_decoder_passthrough.cc(1093)] [GroupMarkerNotSet(crbug.com/242999)!:A0B01900EC060000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content.
[4131:0828/205254.693276:ERROR:gles2_cmd_decoder_passthrough.cc(1093)] [GroupMarkerNotSet(crbug.com/242999)!:A0B01900EC060000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content.
[4131:0828/205254.698842:ERROR:gles2_cmd_decoder_passthrough.cc(1093)] [GroupMarkerNotSet(crbug.com/242999)!:A0B01900EC060000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content.
Anti-Recall: NTQQ Anti-Recall loaded for window: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message
[3973:0828/205255.352279:INFO:CONSOLE(0)] "[2025-08-28 20:52:55.351] [ERROR] [QLogger] [message/AioTimestampService] [clearMsgListTimestamp]newMsgList is undefined", source: /opt/QQ/resources/app/application.asar/renderer/15787.js (0)
[1][274760207]DroppedFrame(1): host_id=1, time=274626736, latest_seq=90, interval=16659
Anti-Recall: Warning: Db is null, no previous msg available.
Anti-Recall: Warning: Db is null, no previous msg available.
Anti-Recall: Warning: Db is null, no previous msg available.
Anti-Recall: Warning: Db is null, no previous msg available.
Anti-Recall: Warning: Db is null, no previous msg available.
Anti-Recall: Warning: Db is null, no previous msg available.
[3973:0828/205255.778938:INFO:CONSOLE(0)] "windowSetup sandboxed: undefined", source: node:electron/js2c/sandbox_bundle (0)
[3973:0828/205255.779026:INFO:CONSOLE(0)] "windowSetup isWebView: false", source: node:electron/js2c/sandbox_bundle (0)
[3973:0828/205255.860265:INFO:CONSOLE(0)] "Uncaught (in promise) Error: Error invoking remote method 'LiteLoader.anti_recall.getNowConfig': Error: No handler registered for 'LiteLoader.anti_recall.getNowConfig'", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)
[3973:0828/205255.860319:INFO:CONSOLE(0)] "Uncaught (in promise) Error: Error invoking remote method 'LiteLoader.anti_recall.getNowConfig': Error: No handler registered for 'LiteLoader.anti_recall.getNowConfig'", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)
[3973:0828/205255.875878:INFO:CONSOLE(0)] "Uncaught (in promise) Error: Error invoking remote method 'LiteLoader.anti_recall.getNowConfig': Error: No handler registered for 'LiteLoader.anti_recall.getNowConfig'", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)
[3973:0828/205255.882802:INFO:CONSOLE(0)] "Uncaught (in promise) Error: Error invoking remote method 'LiteLoader.anti_recall.getNowConfig': Error: No handler registered for 'LiteLoader.anti_recall.getNowConfig'", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)
[3973:0828/205255.883228:INFO:CONSOLE(0)] "Uncaught (in promise) Error: Error invoking remote method 'LiteLoader.anti_recall.getNowConfig': Error: No handler registered for 'LiteLoader.anti_recall.getNowConfig'", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)
[3973:0828/205255.883443:INFO:CONSOLE(0)] "Uncaught (in promise) Error: Error invoking remote method 'LiteLoader.anti_recall.getNowConfig': Error: No handler registered for 'LiteLoader.anti_recall.getNowConfig'", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)
[3973:0828/205255.883580:INFO:CONSOLE(0)] "Uncaught (in promise) Error: Error invoking remote method 'LiteLoader.anti_recall.getNowConfig': Error: No handler registered for 'LiteLoader.anti_recall.getNowConfig'", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)
[3973:0828/205255.883618:INFO:CONSOLE(0)] "Uncaught (in promise) Error: Error invoking remote method 'LiteLoader.anti_recall.getNowConfig': Error: No handler registered for 'LiteLoader.anti_recall.getNowConfig'", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)
[3973:0828/205255.883667:INFO:CONSOLE(0)] "Uncaught (in promise) Error: Error invoking remote method 'LiteLoader.anti_recall.getNowConfig': Error: No handler registered for 'LiteLoader.anti_recall.getNowConfig'", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)
[3973:0828/205255.883715:INFO:CONSOLE(0)] "Uncaught (in promise) Error: Error invoking remote method 'LiteLoader.anti_recall.getNowConfig': Error: No handler registered for 'LiteLoader.anti_recall.getNowConfig'", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)
Anti-Recall: Detected recall, intercepted
Anti-Recall: Detected recall, intercepted
[3973:0828/205256.471164:INFO:CONSOLE(0)] "[Anti-Recall] 尝试反撤回消息ID 7543618575157630683", source: local:////opt/LiteLoaderQQNT/plugins/qq-anti-reccall/renderer.js (0)
Anti-Recall: Detected recall, intercepted
Anti-Recall: Detected recall, intercepted
[3973:0828/205256.474905:INFO:CONSOLE(0)] "[Anti-Recall] 尝试反撤回消息ID 7543618575157630683", source: local:////opt/LiteLoaderQQNT/plugins/qq-anti-reccall/renderer.js (0)
[3973:0828/205256.475299:INFO:CONSOLE(0)] "[Anti-Recall] 尝试反撤回消息ID 7543618575157630683", source: local:////opt/LiteLoaderQQNT/plugins/qq-anti-reccall/renderer.js (0)
[3973:0828/205256.475895:INFO:CONSOLE(0)] "[Anti-Recall] 尝试反撤回消息ID 7543618575157630683", source: local:////opt/LiteLoaderQQNT/plugins/qq-anti-reccall/renderer.js (0)
20:52:57.942 › [198f0bcea85][hot update] ------------ app 启动分界线 ------------
20:52:57.978 › [198f0bcea85][hot update] hotUpdateApi checkHasMultipleQQ:  false
20:52:57.980 › [198f0bcea85][hot update] hotUpdateApi clearOldVersions start
20:52:57.983 › [198f0bcea85][hot update] {
  "baseVersion": "3.2.19-38626",
  "curVersion": "3.2.19-38626",
  "prevVersion": "",
  "onErrorVersions": [],
  "buildId": "38626",
  "unzipRetryCount": 0
}
20:52:57.985 › [198f0bcea85][hot update] dnsDefaultOrder:verbatim
20:52:58.125 › [198f0bcea85][hot update] ----- startUpdate -----
20:52:58.142 › [198f0bcea85][hot update] hotUpdateApi checkHasMultipleQQ:  false
20:52:58.147 › [198f0bcea85][hot update] hotUpdateApi start check  3.2.19-38626  IsOnErrorVersion
20:52:58.147 › [198f0bcea85][hot update] hotUpdateApi checkIsOnErrorVersion result: false
20:52:58.149 › [198f0bcea85][hot update] [startUpdate] 无需更新
[4201:0828/205258.340036:INFO:perf_util.cc(137)] ListenLowPerformanceNotification: policy=(60, 10, 5, 200, 5000), severe_slot=49, isolate=0x27cc0017c000, has_context=1
[3973:0828/205301.144621:INFO:CONSOLE(0)] "windowSetup sandboxed: undefined", source: node:electron/js2c/sandbox_bundle (0)
[3973:0828/205301.144665:INFO:CONSOLE(0)] "windowSetup isWebView: false", source: node:electron/js2c/sandbox_bundle (0)
[BuglyManager.cpp][UploadBugly][107]!!!in UploadBugly.
[NativeCrashHandler.cpp][getCrashDetailBeanFromRecord][52]!!!! in NativeCrashHandler getCrashDetailBeanFromRecord, open file error!!!,dumpFilePath:/home/Mashu/.config/QQ/crash_files/rqd_record.eup.
[NativeCrashHandler.cpp][uploadCrashEvent][331]get null crashDetailBean, return!
98 js loaded
```
